openapi: 3.0.0
info:
  title: Competitor Analysis API
  version: 1.0.0
  description: API para obtener un análisis de competencia con información clave de empresas competidoras.
paths:
  /competitor-analysis:
    post:
      summary: Generar análisis de competencia
      description: Devuelve una lista de competidores con información detallada sobre su producto, mercado y análisis DAFO en comparación con la empresa del usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company_name:
                  type: string
                  description: Nombre de la empresa del usuario
                website:
                  type: string
                  description: URL del sitio web del usuario
                mission:
                  type: string
                  description: Misión de la empresa del usuario
              required:
                - company_name
                - website
                - mission
      responses:
        '200':
          description: Lista de competidores con análisis comparativo
          content:
            application/json:
              schema:
                type: object
                properties:
                  competitor_analysis:
                    type: array
                    items:
                      $ref: '#/components/schemas/Competitor'
  
  /api/v1/competitors:
    get:
      summary: Get all competitors
      description: Retrieve a list of all competitors
      operationId: get_competitors
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitorsResponse'
    post:
      summary: Add a new competitor
      description: Add a new competitor to track
      operationId: add_competitor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompetitorRequest'
      responses:
        '201':
          description: Competitor created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitorResponse'
  
  /api/v1/competitors/{competitor_id}:
    get:
      summary: Get competitor by ID
      description: Retrieve a specific competitor by ID
      operationId: get_competitor
      parameters:
        - name: competitor_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitorResponse'
    put:
      summary: Update competitor
      description: Update an existing competitor
      operationId: update_competitor
      parameters:
        - name: competitor_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompetitorRequest'
      responses:
        '200':
          description: Competitor updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitorResponse'
    delete:
      summary: Delete competitor
      description: Delete a competitor by ID
      operationId: delete_competitor
      parameters:
        - name: competitor_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Competitor deleted

components:
  schemas:
    CompetitorAnalysisRequest:
      type: object
      properties:
        company_name:
          type: string
          description: Nombre de la empresa del usuario
        website:
          type: string
          description: URL del sitio web del usuario
        mission:
          type: string
          description: Misión de la empresa del usuario
      required:
        - company_name
        - website
        - mission
    
    CompetitorAnalysisResponse:
      type: object
      properties:
        competitor_analysis:
          type: array
          items:
            $ref: '#/components/schemas/Competitor'
            
    Competitor:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        website:
          type: string
        description:
          type: string
        score_affinity:
          type: number
          minimum: 0
          maximum: 10
          description: Nivel de afinidad con la empresa del usuario (0-10)
        product:
          type: object
          properties:
            features:
              type: array
              items:
                type: string
            use_cases:
              type: array
              items:
                type: string
            pricing:
              type: object
              properties:
                model:
                  type: string
                  enum:
                    - SaaS
                    - one-time purchase
                    - freemium
                    - enterprise-only
                  description: Modelo de negocio
                plans:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      price:
                        type: number
                      features:
                        type: array
                        items:
                          type: string
                discounts:
                  type: array
                  items:
                    type: string
        market:
          type: object
          properties:
            target_audience:
              type: object
              properties:
                sectors:
                  type: array
                  items:
                    type: string
                    enum:
                      - Technology
                      - Finance
                      - Healthcare
                      - Retail
                      - Education
                company_size:
                  type: array
                  items:
                    type: string
                    enum:
                      - Startup
                      - Small Business
                      - Medium Enterprise
                      - Large Corporation
                decision_maker:
                  type: array
                  items:
                    type: string
            market_presence:
              type: object
              properties:
                countries:
                  type: array
                  items:
                    type: string
                languages:
                  type: array
                  items:
                    type: string
                    enum:
                      - English
                      - Spanish
                      - French
                      - German
                      - Chinese
            business_segments:
              type: array
              items:
                type: string
        swot_analysis:
          type: object
          properties:
            strengths:
              type: array
              items:
                type: string
            weaknesses:
              type: array
              items:
                type: string
            opportunities:
              type: array
              items:
                type: string
            threats:
              type: array
              items:
                type: string

    CompetitorRequest:
      type: object
      properties:
        name:
          type: string
        website:
          type: string
        description:
          type: string
        score_affinity:
          type: number
          minimum: 0
          maximum: 10
        product:
          $ref: '#/components/schemas/Product'
        market:
          $ref: '#/components/schemas/Market'
        swot_analysis:
          $ref: '#/components/schemas/SwotAnalysis'
      required:
        - name
        - website
    
    Product:
      type: object
      properties:
        features:
          type: array
          items:
            type: string
        use_cases:
          type: array
          items:
            type: string
        pricing:
          $ref: '#/components/schemas/Pricing'
    
    Pricing:
      type: object
      properties:
        model:
          type: string
          enum:
            - SaaS
            - one-time purchase
            - freemium
            - enterprise-only
        plans:
          type: array
          items:
            $ref: '#/components/schemas/PricingPlan'
        discounts:
          type: array
          items:
            type: string
    
    PricingPlan:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
        features:
          type: array
          items:
            type: string
    
    Market:
      type: object
      properties:
        target_audience:
          $ref: '#/components/schemas/TargetAudience'
        market_presence:
          $ref: '#/components/schemas/MarketPresence'
        business_segments:
          type: array
          items:
            type: string
    
    TargetAudience:
      type: object
      properties:
        sectors:
          type: array
          items:
            type: string
            enum:
              - Technology
              - Finance
              - Healthcare
              - Retail
              - Education
        company_size:
          type: array
          items:
            type: string
            enum:
              - Startup
              - Small Business
              - Medium Enterprise
              - Large Corporation
        decision_maker:
          type: array
          items:
            type: string
    
    MarketPresence:
      type: object
      properties:
        countries:
          type: array
          items:
            type: string
        languages:
          type: array
          items:
            type: string
            enum:
              - English
              - Spanish
              - French
              - German
              - Chinese
    
    SwotAnalysis:
      type: object
      properties:
        strengths:
          type: array
          items:
            type: string
        weaknesses:
          type: array
          items:
            type: string
        opportunities:
          type: array
          items:
            type: string
        threats:
          type: array
          items:
            type: string
    
    CompetitorResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Competitor'
        message:
          type: string
    
    CompetitorsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Competitor'
        total:
          type: integer
        page:
          type: integer
        page_size:
          type: integer
        message:
          type: string